repos:
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        types: [python]
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        types: [python]
        args:
            - --check
