services:
  webserver:
    image: ghcr.io/ucfopen/materia:webserver-dev
    build:
      context: ../
      dockerfile: materia-webserver.Dockerfile
    ports:
      - "80:80" # main materia
      - "443:443" # main materia
    networks:
      - frontend
    depends_on:
      - app

  app:
    image: ghcr.io/ucfopen/materia:app-dev
    build:
      context: ../
      dockerfile: materia-app.Dockerfile
    env_file:
      .env
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: materia_frontend
  backend:
    name: materia_backend

