# Generated by Django 5.0.1 on 2024-05-17 18:27
import logging
from itertools import islice
from datetime import datetime

from django.db import migrations, models
from django.utils import timezone

logger = logging.getLogger("django")


def chunk_ids(num_ids, chunk_size):
    """
    Used to split large number of IDs into smaller chunks for processing
    """
    id_list = list(range(1, num_ids + 1))
    for i in range(0, len(id_list), chunk_size):
        yield id_list[i : i + chunk_size]


def translate_timestamps(apps, schema_editor):
    """
    Convert Unix epoch timestamp to datetime. (Forwards migration)
    """

    def timestamp_to_datetime(ts):
        if ts is None:
            return None
        if ts == -1:
            return None

        return timezone.make_aware(datetime.fromtimestamp(ts))

    logger.info("Converting Asset timestamps to datetimes")
    Asset = apps.get_model("core", "Asset")
    all_assets = Asset.objects.all()
    for asset in all_assets:
        asset.created_at_dt = timestamp_to_datetime(asset.created_at)
        asset.deleted_at_dt = timestamp_to_datetime(asset.deleted_at)
    Asset.objects.bulk_update(
        all_assets, ["created_at_dt", "deleted_at_dt"], batch_size=1000
    )

    logger.info("Converting AssetData timestamps to datetimes")
    AssetData = apps.get_model("core", "AssetData")
    all_asset_data = AssetData.objects.all()
    for asset_data in all_asset_data:
        asset_data.created_at_dt = timestamp_to_datetime(asset_data.created_at)
    AssetData.objects.bulk_update(all_asset_data, ["created_at_dt"], batch_size=1000)

    logger.info("Converting DateRange timestamps to datetimes")
    DateRange = apps.get_model("core", "DateRange")
    all_date_ranges = DateRange.objects.all()
    for date_range in all_date_ranges:
        date_range.start_at_dt = timestamp_to_datetime(date_range.start_at)
        date_range.end_at_dt = timestamp_to_datetime(date_range.end_at)
    DateRange.objects.bulk_update(
        all_date_ranges, ["start_at_dt", "end_at_dt"], batch_size=1000
    )

    logger.info("Converting Log timestamps to datetimes")
    Log = apps.get_model("core", "Log")
    # Different batch strategy for massive tables like Log
    # split into smaller batches of logs to avoid memory issues
    for ids in chunk_ids(Log.objects.last().id, 1000):
        print("Processing Log IDs:", ids[0], "to", ids[-1])
        batch_logs = Log.objects.filter(id__in=ids)
        for log in batch_logs:
            log.created_at_dt = timestamp_to_datetime(log.created_at)
        Log.objects.bulk_update(batch_logs, ["created_at_dt"])

    logger.info("Converting LogActivity timestamps to datetimes")
    LogActivity = apps.get_model("core", "LogActivity")
    all_log_activities = LogActivity.objects.all()
    for log_activity in all_log_activities:
        log_activity.created_at_dt = timestamp_to_datetime(log_activity.created_at)
    LogActivity.objects.bulk_update(
        all_log_activities, ["created_at_dt"], batch_size=1000
    )

    logger.info("Converting LogPlay timestamps to datetimes")
    LogPlay = apps.get_model("core", "LogPlay")
    # Different batch strategy for massive tables like LogPlay
    # split into smaller batches of logs to avoid memory issues
    for ids in chunk_ids(LogPlay.objects.last().id, 1000):
        print("Processing LogPlay IDs:", ids[0], "to", ids[-1])
        batch_logplays = LogPlay.objects.filter(id__in=ids)
        for logplay in batch_logplays:
            logplay.created_at_dt = timestamp_to_datetime(log.created_at)
        LogPlay.objects.bulk_update(batch_logplays, ["created_at_dt"])

    logger.info("Converting LogStorage timestamps to datetimes")
    LogStorage = apps.get_model("core", "LogStorage")
    all_log_storages = LogStorage.objects.all()
    for log_storage in all_log_storages:
        log_storage.created_at_dt = timestamp_to_datetime(log_storage.created_at)
    LogStorage.objects.bulk_update(all_log_storages, ["created_at_dt"], batch_size=1000)

    logger.info("Converting Lti timestamps to datetimes")
    Lti = apps.get_model("core", "Lti")
    all_ltis = Lti.objects.all()
    for lti in all_ltis:
        lti.created_at_dt = timestamp_to_datetime(lti.created_at)
        lti.updated_at_dt = timestamp_to_datetime(lti.updated_at)
    Lti.objects.bulk_update(
        all_ltis, ["created_at_dt", "updated_at_dt"], batch_size=1000
    )

    logger.info("Converting Notification timestamps to datetimes")
    Notification = apps.get_model("core", "Notification")
    all_notifications = Notification.objects.all()
    for notification in all_notifications:
        notification.created_at_dt = timestamp_to_datetime(notification.created_at)
        notification.updated_at_dt = timestamp_to_datetime(notification.updated_at)
    Notification.objects.bulk_update(
        all_notifications, ["created_at_dt", "updated_at_dt"], batch_size=1000
    )

    logger.info("Converting PermObjectToUser timestamps to datetimes")
    PermObjectToUser = apps.get_model("core", "PermObjectToUser")
    all_potus = PermObjectToUser.objects.all()
    for potu in all_potus:
        potu.expires_at_dt = timestamp_to_datetime(potu.expires_at)
    PermObjectToUser.objects.bulk_update(all_potus, ["expires_at_dt"], batch_size=1000)

    logger.info("Converting UserExtraAttempts timestamps to datetimes")
    UserExtraAttempts = apps.get_model("core", "UserExtraAttempts")
    all_ueas = UserExtraAttempts.objects.all()
    for uea in all_ueas:
        uea.created_at_dt = timestamp_to_datetime(uea.created_at)
    UserExtraAttempts.objects.bulk_update(all_ueas, ["created_at_dt"], batch_size=1000)

    logger.info("Converting Question timestamps to datetimes")
    Question = apps.get_model("core", "Question")
    all_questions = Question.objects.all()
    for question in all_questions:
        question.created_at_dt = timestamp_to_datetime(question.created_at)
    Question.objects.bulk_update(all_questions, ["created_at_dt"], batch_size=1000)

    logger.info("Converting Widget timestamps to datetimes")
    Widget = apps.get_model("core", "Widget")
    all_widgets = Widget.objects.all()
    for widget in all_widgets:
        widget.created_at_dt = timestamp_to_datetime(widget.created_at)
    Widget.objects.bulk_update(all_widgets, ["created_at_dt"], batch_size=1000)

    logger.info("Converting WidgetInstance timestamps to datetimes")
    WidgetInstance = apps.get_model("core", "WidgetInstance")
    all_wis = WidgetInstance.objects.all()
    for wi in all_wis:
        wi.created_at_dt = timestamp_to_datetime(wi.created_at)
    WidgetInstance.objects.bulk_update(all_wis, ["created_at_dt"], batch_size=1000)

    logger.info("Converting WidgetQset timestamps to datetimes")
    WidgetQset = apps.get_model("core", "WidgetQset")
    all_wqets = WidgetQset.objects.all()
    for wq in all_wqets:
        wq.created_at_dt = timestamp_to_datetime(wq.created_at)
    WidgetQset.objects.bulk_update(all_wqets, ["created_at_dt"], batch_size=1000)


def translate_datetimes(apps, schema_editor):
    """
    Convert datetime back to Unix epoch timestamp. (backwards migration)
    """

    def datetime_to_timestamp(dt):
        if dt is None:
            return -1

        return datetime.timestamp(dt)

    logger.info("Converting Asset datetimes to timestamps")
    Asset = apps.get_model("core", "Asset")
    all_assets = Asset.objects.all()
    for asset in all_assets:
        asset.created_at = datetime_to_timestamp(asset.created_at_dt)
        asset.deleted_at = datetime_to_timestamp(asset.deleted_at_dt)
    Asset.objects.bulk_update(all_assets, ["created_at", "deleted_at"], batch_size=1000)

    logger.info("Converting AssetData datetimes to timestamps")
    AssetData = apps.get_model("core", "AssetData")
    all_asset_data = AssetData.objects.all()
    for asset_data in all_asset_data:
        asset_data.created_at = datetime_to_timestamp(asset_data.created_at_dt)
    AssetData.objects.bulk_update(all_asset_data, ["created_at"], batch_size=1000)

    logger.info("Converting DateRange datetimes to timestamps")
    DateRange = apps.get_model("core", "DateRange")
    all_date_ranges = DateRange.objects.all()
    for date_range in all_date_ranges:
        date_range.start_at = datetime_to_timestamp(date_range.start_at_dt)
        date_range.end_at = datetime_to_timestamp(date_range.end_at_dt)
    DateRange.objects.bulk_update(
        all_date_ranges, ["start_at", "end_at"], batch_size=1000
    )

    logger.info("Converting Log datetimes to timestamps")
    Log = apps.get_model("core", "Log")
    all_log_activities = Log.objects.all()
    for log in all_log_activities:
        log.created_at = datetime_to_timestamp(log.created_at_dt)
    Log.objects.bulk_update(all_log_activities, ["created_at"], batch_size=1000)

    logger.info("Converting LogActivity datetimes to timestamps")
    LogActivity = apps.get_model("core", "LogActivity")
    all_log_activities = LogActivity.objects.all()
    for log_activity in all_log_activities:
        log_activity.created_at = datetime_to_timestamp(log_activity.created_at_dt)
    LogActivity.objects.bulk_update(all_log_activities, ["created_at"], batch_size=1000)

    logger.info("Converting LogPlay datetimes to timestamps")
    LogPlay = apps.get_model("core", "LogPlay")
    all_log_plays = LogPlay.objects.all()
    for log_play in all_log_plays:
        log_play.created_at = datetime_to_timestamp(log_play.created_at_dt)
    LogPlay.objects.bulk_update(all_log_plays, ["created_at"], batch_size=1000)

    logger.info("Converting LogStorage datetimes to timestamps")
    LogStorage = apps.get_model("core", "LogStorage")
    all_log_storages = LogStorage.objects.all()
    for log_storage in all_log_storages:
        log_storage.created_at = datetime_to_timestamp(log_storage.created_at_dt)
    LogStorage.objects.bulk_update(all_log_storages, ["created_at"], batch_size=1000)

    logger.info("Converting Lti datetimes to timestamps")
    Lti = apps.get_model("core", "Lti")
    all_ltis = Lti.objects.all()
    for lti in all_ltis:
        lti.created_at = datetime_to_timestamp(lti.created_at_dt)
        lti.updated_at = datetime_to_timestamp(lti.updated_at_dt)
    Lti.objects.bulk_update(all_ltis, ["created_at", "updated_at"], batch_size=1000)

    logger.info("Converting Notification datetimes to timestamps")
    Notification = apps.get_model("core", "Notification")
    all_notifications = Notification.objects.all()
    for notification in all_notifications:
        notification.created_at = datetime_to_timestamp(notification.created_at_dt)
        notification.updated_at = datetime_to_timestamp(notification.updated_at_dt)
    Notification.objects.bulk_update(
        all_notifications, ["created_at", "updated_at"], batch_size=1000
    )

    logger.info("Converting PermObjectToUser datetimes to timestamps")
    PermObjectToUser = apps.get_model("core", "PermObjectToUser")
    all_potus = PermObjectToUser.objects.all()
    for potu in all_potus:
        potu.expires_at = datetime_to_timestamp(potu.expires_at_dt)
    PermObjectToUser.objects.bulk_update(all_potus, ["expires_at"], batch_size=1000)

    logger.info("Converting UserExtraAttempts datetimes to timestamps")
    UserExtraAttempts = apps.get_model("core", "UserExtraAttempts")
    all_ueas = UserExtraAttempts.objects.all()
    for uea in all_ueas:
        uea.created_at = datetime_to_timestamp(uea.created_at_dt)
    UserExtraAttempts.objects.bulk_update(all_ueas, ["created_at"], batch_size=1000)

    logger.info("Converting Question datetimes to timestamps")
    Question = apps.get_model("core", "Question")
    all_questions = Question.objects.all()
    for question in all_questions:
        question.created_at = datetime_to_timestamp(question.created_at_dt)
    Question.objects.bulk_update(all_questions, ["created_at"], batch_size=1000)

    logger.info("Converting Widget datetimes to timestamps")
    Widget = apps.get_model("core", "Widget")
    all_widgets = Widget.objects.all()
    for widget in all_widgets:
        widget.created_at = datetime_to_timestamp(widget.created_at_dt)
    Widget.objects.bulk_update(all_widgets, ["created_at"], batch_size=1000)

    logger.info("Converting WidgetInstance datetimes to timestamps")
    WidgetInstance = apps.get_model("core", "WidgetInstance")
    all_wis = WidgetInstance.objects.all()
    for wi in all_wis:
        wi.created_at = datetime_to_timestamp(wi.created_at_dt)
    WidgetInstance.objects.bulk_update(all_wis, ["created_at"], batch_size=1000)

    logger.info("Converting WidgetQset datetimes to timestamps")
    WidgetQset = apps.get_model("core", "WidgetQset")
    all_widgets = WidgetQset.objects.all()
    for wq in all_widgets:
        wq.created_at = datetime_to_timestamp(wq.created_at_dt)
    WidgetQset.objects.bulk_update(all_widgets, ["created_at"], batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_log_log_type_alter_logactivity_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="updated_at_dt",
            field=models.DateTimeField(default=timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="permobjecttouser",
            name="expires_at_dt",
            field=models.DateTimeField(default=timezone.now, null=True),
        ),
        # TODO: Determine if we should remove atomic=False for production after testing
        migrations.RunPython(translate_timestamps, translate_datetimes, atomic=False),
    ]
