# Generated by Django 5.0.1 on 2024-05-17 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_log_log_type_alter_logactivity_user_and_more"),
    ]

    operations = [
        # Migration no longer needed
    ]
