# Generated by Django 5.0.1 on 2024-06-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_convert_timestamps_to_datetimes"),
    ]

    operations = [
        # migration no longer needed.
    ]
