# Generated by Django 5.0.1 on 2025-02-06 19:20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_widget_is_generable_and_more"),
    ]

    operations = [
        # Don't need this migration anymore.
    ]
