# Generated by Django 5.0.1 on 2025-03-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_merge_20250305_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetqset',
            name='data',
            field=models.TextField(db_column='data'),
        ),
        migrations.RenameField(
            model_name='widgetqset',
            old_name='data',
            new_name='_data',
        ),
        migrations.AlterField(
            model_name='widgetinstance',
            name='close_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='widgetinstance',
            name='open_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='widgetinstance',
            name='updated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
